before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - briandquinn@gmail.com
branches:
  only:
    - master
    - 1-1-stable
rvm:
  - 1.8.7
  - 1.9.3
